// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNRcsTEm984N2K6g2wTqphu9EL5JW6lAI',
    appId: '1:814139403815:web:f0e77658664526d1bd6802',
    messagingSenderId: '814139403815',
    projectId: 'nero-doctor',
    authDomain: 'nero-doctor.firebaseapp.com',
    storageBucket: 'nero-doctor.firebasestorage.app',
    measurementId: 'G-EL7MLQ3YPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbS0xISSCy_ls5vwinWrrkP6TPa8fB7gM',
    appId: '1:814139403815:android:00b8d05a4519ab90bd6802',
    messagingSenderId: '814139403815',
    projectId: 'nero-doctor',
    storageBucket: 'nero-doctor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx1wDnkJUaHmBnGqjDzDWiJs8nBe00ZLk',
    appId: '1:814139403815:ios:8ab23745e69a42b7bd6802',
    messagingSenderId: '814139403815',
    projectId: 'nero-doctor',
    storageBucket: 'nero-doctor.firebasestorage.app',
    iosBundleId: 'com.example.merodoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx1wDnkJUaHmBnGqjDzDWiJs8nBe00ZLk',
    appId: '1:814139403815:ios:8ab23745e69a42b7bd6802',
    messagingSenderId: '814139403815',
    projectId: 'nero-doctor',
    storageBucket: 'nero-doctor.firebasestorage.app',
    iosBundleId: 'com.example.merodoctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNRcsTEm984N2K6g2wTqphu9EL5JW6lAI',
    appId: '1:814139403815:web:a52ef53abc88c7fabd6802',
    messagingSenderId: '814139403815',
    projectId: 'nero-doctor',
    authDomain: 'nero-doctor.firebaseapp.com',
    storageBucket: 'nero-doctor.firebasestorage.app',
    measurementId: 'G-V9EFXGKDFY',
  );
}
